[package]
name = "juno-starknet-rs"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
starknet-rs = { git = "https://github.com/lambdaclass/starknet_in_rust", version = "0.1.0" }
