[package]
name = "juno-starknet-rs"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.160"
serde_json = "1.0.96"
felt = { git = "https://github.com/lambdaclass/cairo-rs", package = "cairo-felt", rev = "eebfd612c5f969c759cb982e8fb777b2a1a1dab0" }
starknet-rs = { git = "https://github.com/lambdaclass/starknet_in_rust", rev = "3f275ab4ece93f05d7faddc28eaa3459b405b2a4" }


[lib]
crate-type = ["cdylib", "staticlib"]
