[package]
name = "juno-starknet-rs"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
felt = { git = "https://github.com/lambdaclass/cairo-rs", package = "cairo-felt", rev = "8dba86dbec935fa04a255e2edf3d5d184950fa22" }
starknet-rs = { git = "https://github.com/lambdaclass/starknet_in_rust", rev = "17a7ab24c9eb78f62660da68e6690e5b014a1ac9" }

[lib]
crate-type = ["cdylib", "staticlib"]